### ISSUE TITLE
'Invalid invitation token' not useful to users who already has a password

### ISSUE THREAD

**Issue by dept42** [rymai/devise_invitable#4] opened 2010-09-16 04:22 UTC
If a user has already accepted their invitation and set a password, but then follows their invite link again, they get an 'Invalid invitation token'; this is both useless, in that it doesn't tell them what they need to do, and unnecessary, as we can just redirect them to the sign-in page to enter their password.

I created a patch to do so here: dept42/devise_invitable@bad2cc13299a106c4519f1957143b200596d5803

I'm not particularly thrilled with that, but I couldn't see a better way to do it. Not least of my worries, why in the heck is the user id being passed in as :format?

**Comment by rymai** [comment] 2010-09-16 08:45
Hi,

I'm sorry but your branch is not up to date with my fork.
Moreover you use params[:format] to retrieve a User by id, 2 comments here:
- you should use resource_class & resource_name, resources can be users, but also admins or whatever you want !
- I don't know why you use params[:format] because there is no id at all in the "accept invitation" url, the url is like this: /resources/invitation/accept?invitation_token=abcdef

In the most up-to-date version of the gem, if the token is invalid (blank or doesn't exist in the database), the visitor is redirected to after_sign_out_path_for. You can override after_sign_out_path_for to you "login" path if you'd like.

Please check out the most-up-to-date code here: http://github.com/rymai/devise_invitable/blob/master/app/controllers/devise/invitations_controller.rb

**Comment by dept42** [comment] 2010-09-16 15:56
I know, I didn't bring myself up to date because what I have now is working, and I can't afford to spend a bunch of time debugging a new version right now, in the middle of launching my site. As I said, I don't think my patch is the right solution, and don't expect you to use it verbatim -- I'm just trying to illustrate the problem.

At the version I'm at, invite URLs look like:

/users/invitation/edit.7?invitation_token=nxnRcVaa3WchG4I9zUqB

I have no idea how the user id got into the format field, but I'm glad it shows up somewhere. I'd suggest that a better URL format might be:

/users/7/invitation/accept/nxnRcVaa3WchG4I9zUqB

What do you think?

**Comment by rymai** [comment] 2010-09-16 22:35
I think you call accept_user_invitation_path with a user id.
User id should not appear in invitation's acceptation url.

About your route suggestion, it's a good one, actually I did have the idea before but I can't remember why I kept it like this (as in Devise, using "?invitation_token=xxx"), so I made a branch (http://github.com/rymai/devise_invitable/tree/new_url) where I commited your suggestion (rymai/devise_invitable@f759280496a320833fb353931ee55ddb3db2eeac).

Invitation's acceptation url are now: /resources/invitation/accept/:invitation_token (legacy url /resources/invitation/accept?invitation_token=:invitation_token still work, with the magic Rails 3 optional parameters in routes!)

I wait a little bit to be sure it can be merged in the master branch... (but since legacy urls are still working it should not cause any problem).

**Comment by dept42** [comment] 2010-09-16 22:47
Aha, you're right, it looks like my E-mail template has:

edit_user_invitation_url(@resource, :invitation_token => @resource.invitation_token)

Probably copied it from some outdated template; I doubt I came up with that myself.

In any case, is there a reason /not/ to include the user id in the URL? Do you see what I'm saying about how knowing the state of the user object allows you to provide more relevant feedback?

**Comment by rymai** [comment] 2010-09-16 23:21
Sure I see, but:

1/ Why a confirmed user would re-click on his "accept invitation" link ?
2/ User will never see any url with his id in it, so I think it's better not to show his id in this url either.
3/ Accepting an invitation is done from the invitation_token only, since we don't need User id, we don't pass it in the url

So for all these reason, I prefer redirect the users that re-click on their invitation link to log-in page and show them an "invalid token" notice (if the user is not stupid, he will try to log-in, or request a "reset password") rather than putting users' id in each invitation links, and not using it 90% of the time.

Again, thanks for your input.

**Comment by dept42** [comment] 2010-09-17 00:02
While redirecting to the login page with a flash message would be better for users who have already set a password, it would be confusing for users who DON'T have a password yet, and messed up copying the URL from their browser, or got multiple invitations with different codes (which also, in my opinion, should be prevented), and have clicked the wrong one.

As for why a user would do that, users do all sorts of silly stuff, because they're not really paying attention -- and a user shouldn't HAVE to really be paying close attention in order to successfully navigate logging in to a web app. I don't want my users thinking about how they can manage to log in, I want them thinking about how great my app is.

**Comment by thibaudgg** [comment] 2010-09-17 12:46
I propose:
- accept invitation link should be /:resource/invitation/accept/:invitation_token
- invitation code should not be overwritten by default when resending invitation email
- invitation code should not be cleared when a user accept his invitation (just set a new invitation_accepted_at field). But it'll no more be consistent with how work confirmation_token in Devise (can be an issue)
- user already accepted that re-click invitation link is redirected to after_sign_out_path_for with a message like: "You are already in, please use the login form..."
- user with invalid invitation_token is redirected to after_sign_out_path_for with a message like: "You token is invalid, please contact us...."

What do you think about this proposition?

**Comment by rymai** [comment] 2010-09-17 13:06
Thanks Thibaud!

Sounds great, I agree on all the points!

What do you think Chris ?

**Comment by dept42** [comment] 2010-09-17 15:16
Sounds great! I agree completely.

**Comment by rymai** [comment] 2010-09-28 23:31
Hey guys,

I've implemented what Thibaud suggested ! Check it out here: http://github.com/rymai/devise_invitable/tree/new_url

Hope you like it ! :)

See CHANGELOG for the description of the new behavior.

Thanks for your help on this!

**Closed as completed** 2011-09-27 19:42 UTC
Labels: new feature
